use crate::parser::Element;
pub static PERIODEN_SYSTEM: [Element; 118] = [
    Element {
        name: "Wasserstoff",
        symbol: "H",
        atomaremasse: 1.0081,
        ordnungszahl: 1,
    },
    Element {
        name: "Helium",
        symbol: "He",
        atomaremasse: 4.0026022,
        ordnungszahl: 2,
    },
    Element {
        name: "Lithium",
        symbol: "Li",
        atomaremasse: 6.946,
        ordnungszahl: 3,
    },
    Element {
        name: "Beryllium",
        symbol: "Be",
        atomaremasse: 9.01218315,
        ordnungszahl: 4,
    },
    Element {
        name: "Bor",
        symbol: "B",
        atomaremasse: 10.811,
        ordnungszahl: 5,
    },
    Element {
        name: "Kohlenstoff",
        symbol: "C",
        atomaremasse: 12.01112,
        ordnungszahl: 6,
    },
    Element {
        name: "Stickstoff",
        symbol: "N",
        atomaremasse: 14.006714,
        ordnungszahl: 7,
    },
    Element {
        name: "Sauerstoff",
        symbol: "O",
        atomaremasse: 15.99915,
        ordnungszahl: 8,
    },
    Element {
        name: "Fluor",
        symbol: "F",
        atomaremasse: 18.9984031636,
        ordnungszahl: 9,
    },
    Element {
        name: "Neon",
        symbol: "Ne",
        atomaremasse: 20.17976,
        ordnungszahl: 10,
    },
    Element {
        name: "Natrium",
        symbol: "Na",
        atomaremasse: 22.989769282,
        ordnungszahl: 11,
    },
    Element {
        name: "Magnesium",
        symbol: "Mg",
        atomaremasse: 24.30524,
        ordnungszahl: 12,
    },
    Element {
        name: "Aluminium",
        symbol: "Al",
        atomaremasse: 26.98153857,
        ordnungszahl: 13,
    },
    Element {
        name: "Silicium",
        symbol: "Si",
        atomaremasse: 28.08528,
        ordnungszahl: 14,
    },
    Element {
        name: "Phosphor",
        symbol: "P",
        atomaremasse: 30.9737619985,
        ordnungszahl: 15,
    },
    Element {
        name: "Schwefel",
        symbol: "S",
        atomaremasse: 32.0632,
        ordnungszahl: 16,
    },
    Element {
        name: "Chlor",
        symbol: "Cl",
        atomaremasse: 35.4535,
        ordnungszahl: 17,
    },
    Element {
        name: "Argon",
        symbol: "Ar",
        atomaremasse: 39.9481,
        ordnungszahl: 18,
    },
    Element {
        name: "Kalium",
        symbol: "K",
        atomaremasse: 39.09831,
        ordnungszahl: 19,
    },
    Element {
        name: "Calcium",
        symbol: "Ca",
        atomaremasse: 40.0784,
        ordnungszahl: 20,
    },
    Element {
        name: "Scandium",
        symbol: "Sc",
        atomaremasse: 44.9559085,
        ordnungszahl: 21,
    },
    Element {
        name: "Titan",
        symbol: "Ti",
        atomaremasse: 47.8671,
        ordnungszahl: 22,
    },
    Element {
        name: "Vanadium",
        symbol: "V",
        atomaremasse: 50.94151,
        ordnungszahl: 23,
    },
    Element {
        name: "Chrom",
        symbol: "Cr",
        atomaremasse: 51.99616,
        ordnungszahl: 24,
    },
    Element {
        name: "Mangan",
        symbol: "Mn",
        atomaremasse: 54.9380443,
        ordnungszahl: 25,
    },
    Element {
        name: "Eisen",
        symbol: "Fe",
        atomaremasse: 55.8452,
        ordnungszahl: 26,
    },
    Element {
        name: "Cobalt",
        symbol: "Co",
        atomaremasse: 58.9331944,
        ordnungszahl: 27,
    },
    Element {
        name: "Nickel",
        symbol: "Ni",
        atomaremasse: 58.69344,
        ordnungszahl: 28,
    },
    Element {
        name: "Kupfer",
        symbol: "Cu",
        atomaremasse: 63.5463,
        ordnungszahl: 29,
    },
    Element {
        name: "Zink",
        symbol: "Zn",
        atomaremasse: 65.382,
        ordnungszahl: 30,
    },
    Element {
        name: "Gallium",
        symbol: "Ga",
        atomaremasse: 69.7231,
        ordnungszahl: 31,
    },
    Element {
        name: "Germanium",
        symbol: "Ge",
        atomaremasse: 72.6308,
        ordnungszahl: 32,
    },
    Element {
        name: "Arsen",
        symbol: "As",
        atomaremasse: 74.9215956,
        ordnungszahl: 33,
    },
    Element {
        name: "Selen",
        symbol: "Se",
        atomaremasse: 78.9718,
        ordnungszahl: 34,
    },
    Element {
        name: "Brom",
        symbol: "Br",
        atomaremasse: 79.90479,
        ordnungszahl: 35,
    },
    Element {
        name: "Krypton",
        symbol: "Kr",
        atomaremasse: 83.7982,
        ordnungszahl: 36,
    },
    Element {
        name: "Rubidium",
        symbol: "Rb",
        atomaremasse: 85.46783,
        ordnungszahl: 37,
    },
    Element {
        name: "Strontium",
        symbol: "Sr",
        atomaremasse: 87.621,
        ordnungszahl: 38,
    },
    Element {
        name: "Yttrium",
        symbol: "Y",
        atomaremasse: 88.905842,
        ordnungszahl: 39,
    },
    Element {
        name: "Zirconium",
        symbol: "Zr",
        atomaremasse: 91.2242,
        ordnungszahl: 40,
    },
    Element {
        name: "Niob",
        symbol: "Nb",
        atomaremasse: 92.906372,
        ordnungszahl: 41,
    },
    Element {
        name: "Molybdän",
        symbol: "Mo",
        atomaremasse: 95.951,
        ordnungszahl: 42,
    },
    Element {
        name: "Technetium",
        symbol: "Tc",
        atomaremasse: 98.9063,
        ordnungszahl: 43,
    },
    Element {
        name: "Ruthenium",
        symbol: "Ru",
        atomaremasse: 101.072,
        ordnungszahl: 44,
    },
    Element {
        name: "Rhodium",
        symbol: "Rh",
        atomaremasse: 102.905502,
        ordnungszahl: 45,
    },
    Element {
        name: "Palladium",
        symbol: "Pd",
        atomaremasse: 106.421,
        ordnungszahl: 46,
    },
    Element {
        name: "Silber",
        symbol: "Ag",
        atomaremasse: 107.86822,
        ordnungszahl: 47,
    },
    Element {
        name: "Cadmium",
        symbol: "Cd",
        atomaremasse: 112.4144,
        ordnungszahl: 48,
    },
    Element {
        name: "Indium",
        symbol: "In",
        atomaremasse: 114.8181,
        ordnungszahl: 49,
    },
    Element {
        name: "Zinn",
        symbol: "Sn",
        atomaremasse: 118.7107,
        ordnungszahl: 50,
    },
    Element {
        name: "Antimon",
        symbol: "Sb",
        atomaremasse: 121.7601,
        ordnungszahl: 51,
    },
    Element {
        name: "Tellur",
        symbol: "Te",
        atomaremasse: 127.603,
        ordnungszahl: 52,
    },
    Element {
        name: "Iod",
        symbol: "I",
        atomaremasse: 126.904473,
        ordnungszahl: 53,
    },
    Element {
        name: "Xenon",
        symbol: "Xe",
        atomaremasse: 131.2936,
        ordnungszahl: 54,
    },
    Element {
        name: "Caesium",
        symbol: "Cs",
        atomaremasse: 132.905451966,
        ordnungszahl: 55,
    },
    Element {
        name: "Barium",
        symbol: "Ba",
        atomaremasse: 137.3277,
        ordnungszahl: 56,
    },
    Element {
        name: "Lanthan",
        symbol: "La",
        atomaremasse: 138.905477,
        ordnungszahl: 57,
    },
    Element {
        name: "Cer",
        symbol: "Ce",
        atomaremasse: 140.1161,
        ordnungszahl: 58,
    },
    Element {
        name: "Praseodym",
        symbol: "Pr",
        atomaremasse: 140.907662,
        ordnungszahl: 59,
    },
    Element {
        name: "Neodym",
        symbol: "Nd",
        atomaremasse: 144.2423,
        ordnungszahl: 60,
    },
    Element {
        name: "Promethium",
        symbol: "Pm",
        atomaremasse: 146.9151,
        ordnungszahl: 61,
    },
    Element {
        name: "Samarium",
        symbol: "Sm",
        atomaremasse: 150.362,
        ordnungszahl: 62,
    },
    Element {
        name: "Europium",
        symbol: "Eu",
        atomaremasse: 151.9641,
        ordnungszahl: 63,
    },
    Element {
        name: "Gadolinium",
        symbol: "Gd",
        atomaremasse: 157.253,
        ordnungszahl: 64,
    },
    Element {
        name: "Terbium",
        symbol: "Tb",
        atomaremasse: 158.925352,
        ordnungszahl: 65,
    },
    Element {
        name: "Dysprosium",
        symbol: "Dy",
        atomaremasse: 162.5001,
        ordnungszahl: 66,
    },
    Element {
        name: "Holmium",
        symbol: "Ho",
        atomaremasse: 164.930332,
        ordnungszahl: 67,
    },
    Element {
        name: "Erbium",
        symbol: "Er",
        atomaremasse: 167.2593,
        ordnungszahl: 68,
    },
    Element {
        name: "Thulium",
        symbol: "Tm",
        atomaremasse: 168.934222,
        ordnungszahl: 69,
    },
    Element {
        name: "Ytterbium",
        symbol: "Yb",
        atomaremasse: 173.0451,
        ordnungszahl: 70,
    },
    Element {
        name: "Lutetium",
        symbol: "Lu",
        atomaremasse: 174.96681,
        ordnungszahl: 71,
    },
    Element {
        name: "Hafnium",
        symbol: "Hf",
        atomaremasse: 178.492,
        ordnungszahl: 72,
    },
    Element {
        name: "Tantal",
        symbol: "Ta",
        atomaremasse: 180.947882,
        ordnungszahl: 73,
    },
    Element {
        name: "Wolfram",
        symbol: "W",
        atomaremasse: 183.841,
        ordnungszahl: 74,
    },
    Element {
        name: "Rhenium",
        symbol: "Re",
        atomaremasse: 186.2071,
        ordnungszahl: 75,
    },
    Element {
        name: "Osmium",
        symbol: "Os",
        atomaremasse: 190.233,
        ordnungszahl: 76,
    },
    Element {
        name: "Iridium",
        symbol: "Ir",
        atomaremasse: 192.2173,
        ordnungszahl: 77,
    },
    Element {
        name: "Platin",
        symbol: "Pt",
        atomaremasse: 195.0849,
        ordnungszahl: 78,
    },
    Element {
        name: "Gold",
        symbol: "Au",
        atomaremasse: 196.9665695,
        ordnungszahl: 79,
    },
    Element {
        name: "Quecksilber",
        symbol: "Hg",
        atomaremasse: 200.5923,
        ordnungszahl: 80,
    },
    Element {
        name: "Thallium",
        symbol: "Tl",
        atomaremasse: 204.38204,
        ordnungszahl: 81,
    },
    Element {
        name: "Blei",
        symbol: "Pb",
        atomaremasse: 207.21,
        ordnungszahl: 82,
    },
    Element {
        name: "Bismut",
        symbol: "Bi",
        atomaremasse: 208.980401,
        ordnungszahl: 83,
    },
    Element {
        name: "Polonium",
        symbol: "Po",
        atomaremasse: 209.98,
        ordnungszahl: 84,
    },
    Element {
        name: "Astat",
        symbol: "At",
        atomaremasse: 209.9871,
        ordnungszahl: 85,
    },
    Element {
        name: "Radon",
        symbol: "Rn",
        atomaremasse: 222.0,
        ordnungszahl: 86,
    },
    Element {
        name: "Francium",
        symbol: "Fr",
        atomaremasse: 223.0197,
        ordnungszahl: 87,
    },
    Element {
        name: "Radium",
        symbol: "Ra",
        atomaremasse: 226.0254,
        ordnungszahl: 88,
    },
    Element {
        name: "Actinium",
        symbol: "Ac",
        atomaremasse: 227.0278,
        ordnungszahl: 89,
    },
    Element {
        name: "Thorium",
        symbol: "Th",
        atomaremasse: 232.03774,
        ordnungszahl: 90,
    },
    Element {
        name: "Protactinium",
        symbol: "Pa",
        atomaremasse: 231.035882,
        ordnungszahl: 91,
    },
    Element {
        name: "Uran",
        symbol: "U",
        atomaremasse: 238.028913,
        ordnungszahl: 92,
    },
    Element {
        name: "Neptunium",
        symbol: "Np",
        atomaremasse: 237.0482,
        ordnungszahl: 93,
    },
    Element {
        name: "Plutonium",
        symbol: "Pu",
        atomaremasse: 244.0642,
        ordnungszahl: 94,
    },
    Element {
        name: "Americium",
        symbol: "Am",
        atomaremasse: 243.061375,
        ordnungszahl: 95,
    },
    Element {
        name: "Curium",
        symbol: "Cm",
        atomaremasse: 247.0703,
        ordnungszahl: 96,
    },
    Element {
        name: "Berkelium",
        symbol: "Bk",
        atomaremasse: 247.0,
        ordnungszahl: 97,
    },
    Element {
        name: "Californium",
        symbol: "Cf",
        atomaremasse: 251.0,
        ordnungszahl: 98,
    },
    Element {
        name: "Einsteinium",
        symbol: "Es",
        atomaremasse: 252.0,
        ordnungszahl: 99,
    },
    Element {
        name: "Fermium",
        symbol: "Fm",
        atomaremasse: 257.0951,
        ordnungszahl: 100,
    },
    Element {
        name: "Mendelevium",
        symbol: "Md",
        atomaremasse: 258.0,
        ordnungszahl: 101,
    },
    Element {
        name: "Nobelium",
        symbol: "No",
        atomaremasse: 259.0,
        ordnungszahl: 102,
    },
    Element {
        name: "Lawrencium",
        symbol: "Lr",
        atomaremasse: 266.0,
        ordnungszahl: 103,
    },
    Element {
        name: "Rutherfordium",
        symbol: "Rf",
        atomaremasse: 261.1087,
        ordnungszahl: 104,
    },
    Element {
        name: "Dubnium",
        symbol: "Db",
        atomaremasse: 262.1138,
        ordnungszahl: 105,
    },
    Element {
        name: "Seaborgium",
        symbol: "Sg",
        atomaremasse: 263.1182,
        ordnungszahl: 106,
    },
    Element {
        name: "Bohrium",
        symbol: "Bh",
        atomaremasse: 262.1229,
        ordnungszahl: 107,
    },
    Element {
        name: "Hassium",
        symbol: "Hs",
        atomaremasse: 265.269,
        ordnungszahl: 108,
    },
    Element {
        name: "Meitnerium",
        symbol: "Mt",
        atomaremasse: 268.0,
        ordnungszahl: 109,
    },
    Element {
        name: "Darmstadtium",
        symbol: "Ds",
        atomaremasse: 281.0,
        ordnungszahl: 110,
    },
    Element {
        name: "Roentgenium",
        symbol: "Rg",
        atomaremasse: 280.0,
        ordnungszahl: 111,
    },
    Element {
        name: "Copernicium",
        symbol: "Cn",
        atomaremasse: 277.0,
        ordnungszahl: 112,
    },
    Element {
        name: "Nihonium",
        symbol: "Nh",
        atomaremasse: 287.0,
        ordnungszahl: 113,
    },
    Element {
        name: "Flerovium",
        symbol: "Fl",
        atomaremasse: 289.0,
        ordnungszahl: 114,
    },
    Element {
        name: "Moscovium",
        symbol: "Mc",
        atomaremasse: 288.0,
        ordnungszahl: 115,
    },
    Element {
        name: "Livermorium",
        symbol: "Lv",
        atomaremasse: 293.0,
        ordnungszahl: 116,
    },
    Element {
        name: "Tenness",
        symbol: "Ts",
        atomaremasse: 292.0,
        ordnungszahl: 117,
    },
    Element {
        name: "Oganesson",
        symbol: "Og",
        atomaremasse: 294.0,
        ordnungszahl: 118,
    },
];
